### ISSUE TITLE
Use official App Store badges

### ISSUE THREAD

**Issue by sskylar** [oakstudios/joinmastodon#60]
![](https://drp.mk/i/FpVyWfJ7hg.png)

Both Google and Apple have guidelines on App Store badge uses

![](https://drp.mk/i/yjh20y77n3.png)

![](https://drp.mk/i/FfGZDrVSZb.png)

Could we just use the official ones?

https://developer.apple.com/app-store/marketing/guidelines/
https://play.google.com/intl/en_us/badges/

**Comment by danielgamage** [comment]
so i was looking into this when adding them, but part of the reason is that their aspect ratios are different—the border radii too. so we could (should?), but it wouldn't be fit the nice two-col layout that's in figma

<img width="444" alt="image" src="https://user-images.githubusercontent.com/1642599/182230388-66bebe08-1837-438a-b7d0-7dca87b25b4f.png">

**Comment by danielgamage** [comment]
mm reducing the padding makes sense

cc @tyleemem if you have a preference? i can do any of the above

**Comment by tyleemem** [comment]
Reducing padding would be my preference

**Comment by danielgamage** [comment]
added some ideas and notes [in figma](https://www.figma.com/file/6VgXeLbQCR76VM0A0nIKz5/App-Store-Badges?node-id=0%3A1), but everyone should have edit access (i think?)
